name: "cicd_portfolio"
on:
  push:
    branches:
    - master
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - name: List the directory
      run: |
        ls

    - name: Checkout to root directory
      uses: actions/checkout@v4

    - name: List the directory again
      run: |
        ls

    - name: build a docker image using the dockerfile in root directory
      run: |
        sudo docker build -t henryokiyi/cicd_portfolio .

    - name: Login to dockerhub
      run: |
        sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: push the image built to dockerhub
      run: |
        sudo docker push henryokiyi/cicd_portfolio:latest


    - name: SSH into the instance created
      run: |
        echo "${{ secrets.SSH_KEY }}" >> "sshKey"
        chmod 400 "sshKey"
        ssh -i "sshKey" -o StrictHostKeyChecking=no ubuntu@13.60.157.145
        docker --version
    
    - name: Stop the previous docker container running, pull the new image and run it as a container
      run: |
        sudo docker stop henryokiyi/cicd_portfolio || true
        docker rm -f henryokiyi/cicd_portfolio || true
        sudo docker pull henryokiyi/cicd_portfolio
        sudo docker run -d -p 1234:80 --name cicdPortfolio henryokiyi/cicd_portfolio




















    # - name: SSH into the instance created
    #   run: |
    #     echo "${{ secrets.SSH_KEY }}" > "cicd_portfolio.pem"
    #     chmod 400 "cicd_portfolio.pem"
    #     ssh -i "cicd_portfolio.pem" -o StrictHostKeyChecking=no  ec2-user@ec2-13-48-138-47.eu-north-1.compute.amazonaws.com











