name: "cicd_portfolio"
on:
  push:
    branches:
    - master
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - name: List the directory
      run: |
        ls

    - name: Checkout to root directory
      uses: actions/checkout@v4

    - name: List the directory again
      run: |
        ls